import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

export const messages = [
    "AnyRidge implantları nedir?",
    "AnyRidge implantlarının avantajları nelerdir?",
    "AnyRidge implantları ne zaman piyasaya sürüldü?",
    "AnyRidge implantları anında yükleme için kullanılabilir mi?",
    "AnyRidge implantları hangi kemik yoğunluklarını karşılayabilir?",
    "AnyRidge implantları sınırlı ridge genişliği veya derinliği olan hastalar için uygun mudur?",
    "AnyRidge implantlarını estetik olarak üstün kılan nedir?",
    "Doğru AnyRidge implantını nasıl seçebilirim?",
    "AnyRidge implantlarının etkinliğini destekleyen klinik sonuçlar nelerdir?",
    "AnyRidge implantları nedir?",
    "AnyRidge implantlarının avantajları nelerdir?",
    "AnyRidge implantlarının klinik sonuçları nelerdir?",
    "Hangi kemik yoğunluklarında AnyRidge implantları kullanılabilir?",
    "AnyRidge implantları anında yükleme için uygun mu?",
    "AnyRidge implantlarının estetik avantajları nelerdir?",
    "Hangi tür hastalar için AnyRidge implantları uygundur?",
    "AnyRidge implantlarının tedavi süresi ne kadar sürer?",
    "AnyRidge implantlarını nasıl seçmeliyim?",
    "AnyRidge implantlarının uzun vadeli dayanıklılığı nasıldır?",
    "AnyRidge implantları hangi durumlarda kullanılabilir?",
    "AnyRidge implantlarının yerleştirilmesi ne kadar sürer?",
    "AnyRidge implantları ile ilgili en yaygın yan etkiler nelerdir?",
    "AnyRidge implantlarının bakımını nasıl yapmalıyım?",
    "AnyRidge implantlarının fiyat aralığı nedir?",
    "AnyRidge implantları için garanti süresi nedir?",
    "AnyRidge implantları hangi tip hastalar için uygundur?",
    "AnyRidge implantlarının yüzey özellikleri nelerdir?",
    "AnyRidge implantlarının uzun vadeli başarısı nasıldır?",
    "AnyRidge implantları ile ilgili en sık karşılaşılan sorunlar nelerdir?",
    "AnyRidge implantları hangi avantajları sunar?",
    "AnyRidge implantlarının yüzey özellikleri nelerdir?",
    "AnyRidge implantlarının yerleştirilmesi sırasında nelere dikkat edilmelidir?",
    "AnyRidge implantları hangi durumlarda önerilir?",
    "AnyRidge implantlarının uzun vadeli başarısı nasıldır?",
    "AnyRidge implantları ile ilgili en sık karşılaşılan sorunlar nelerdir?",
    "AnyRidge implantlarının fiyat aralığı nedir?",
    "AnyRidge implantları kimler için uygundur?",
    "AnyRidge implantlarının bakımı nasıl yapılmalıdır?",
    "AnyRidge implantlarının yerleştirilmesi ne kadar sürer?",
    "AnyRidge implantlarının avantajları nelerdir?",
    "AnyRidge implantlarının yüzey özellikleri nelerdir?",
    "AnyRidge implantlarının yerleştirilmesi sırasında nelere dikkat edilmelidir?",
    "AnyRidge implantları hangi durumlarda önerilir?",
    "AnyRidge implantlarının uzun vadeli başarısı nasıldır?",
    "AnyRidge implantları ile ilgili en sık karşılaşılan sorunlar nelerdir?",
    "AnyRidge implantlarının fiyat aralığı nedir?",
    "AnyRidge implantları kimler için uygundur?",
    "AnyRidge implantlarının bakımı nasıl yapılmalıdır?",
    "AnyRidge implantlarının yerleştirilmesi ne kadar sürer?",
    "AnyRidge implantları kimler için uygundur?",
    "Sınırlı ridge genişliği olan hastalar için AnyRidge implantları uygun mu?",
    "Düşük kemik yoğunluğu olan hastalar için AnyRidge implantları uygun mu?",
    "Anında yükleme gerektiren durumlarda AnyRidge implantları kullanılabilir mi?",
    "Yaşlı hastalar için AnyRidge implantları uygun mu?",
    "Diş eti hastalığı geçmişi olan hastalar için AnyRidge implantları uygun mu?",
    "Sigarayı bırakan hastalar için AnyRidge implantları uygun mu?",
    "Daha önce diş implantı takılmış ancak başarısız olmuş hastalar için AnyRidge implantları uygun mu?",
    "Diş kaybı yaşayan genç yetişkinler için AnyRidge implantları uygun mu?",
    "Kemik grefti gerektiren durumlarda AnyRidge implantları kullanılabilir mi?",
];
